server:
  port: 8080

spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: test
    initialization-mode: always

  jpa:
    hibernate:
      ddl-auto: create-drop
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      default:
        contentType: application/json
      bindings:
        userActivityChannel:
          destination: userActivity

debug: true

upload:
  dir: /home/sujit/clusus/projects/pet-store

