version: "3.7"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: test
    ports:
    - 5432:5432
#  userservice:
#    build:
#      context: user-service
#      dockerfile: Dockerfile
#    image: sujit/user_service_spring:latest
#    ports:
#    - 8082:8082
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
#      SPRING_DATASOURCE_USERNAME: postgres
#      SPRING_DATASOURCE_PASSWORD: test
#    links:
#      - db
#  petservice:
#    build:
#      context: pet-service
#      dockerfile: Dockerfile
#    image: sujit/pet_service_spring:latest
#    ports:
#    - 8080:8080
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
#      SPRING_DATASOURCE_USERNAME: postgres
#      SPRING_DATASOURCE_PASSWORD: test
#    links:
#      - db
#  storeservice:
#    build:
#      context: store-service
#      dockerfile: Dockerfile
#    image: sujit/order_store_service_spring:latest
#    ports:
#    - 8081:8081
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
#      SPRING_DATASOURCE_USERNAME: postgres
#      SPRING_DATASOURCE_PASSWORD: test
#    links:
#      - db
