server:
  port: 8082


spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: test
    initialization-mode: always

  jpa:
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  cloud:
    stream:
      bindings:
        input:
          destination: userActivity
          group: userActivityQueue

debug: true
